spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
  eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/